/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.evaluacion1.views;

import java.awt.BorderLayout;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import uni.evaluacion1.controllers.PnlVehicleController;
import uni.evaluacion1.controllers.PnlViewVehicleController;
import uni.evaluacion1.views.panels.PnlViewVehicle;

/**
 *
 * @author Ariel Roa
 */
public class IFrmVehicle extends javax.swing.JInternalFrame {

    private PnlViewVehicle pnlViewVehicle;
    private PnlViewVehicleController pnlViewVehicleController;
    private DlgVehicle dlgVehicle;
    private int index;
    
    /**
     * Creates new form IFrmVehicle
     */
    public IFrmVehicle() {
        initComponents();
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }
    
    public void addPropertySupport(PropertyChangeListener pc1){
        
        pnlViewVehicleController.addPropertyChangeListener(pc1);
    }
    
    public void removePropertySupport(PropertyChangeListener pc1){
        
        pnlViewVehicleController.removePropertyChangeListener(pc1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View");

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        pnlContent.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pnlViewVehicle = new PnlViewVehicle();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicle);

        pnlContent.add(pnlViewVehicle, BorderLayout.CENTER);
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 735, 497);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        dlgVehicle = new DlgVehicle(null, true);
        dlgVehicle.addPropertySupport(pnlViewVehicleController.getTblViewModel());
        dlgVehicle.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        dlgVehicle = new DlgVehicle(null, true);
        index = pnlViewVehicle.getTblViewVehicle().getSelectedRow();
        
        if(index >= 0){
            dlgVehicle.addPropertySupport(pnlViewVehicleController.getTblViewModel());
            
            try {
                dlgVehicle.setPnlVehicleController(new PnlVehicleController(dlgVehicle.getPnlVehicleController().updateVehicle(index)));
            } catch (IOException ex) {
                Logger.getLogger(IFrmVehicle.class.getName()).log(Level.SEVERE, null, ex);
            }
            dlgVehicle.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para actualizar.", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        index = pnlViewVehicle.getTblViewVehicle().getSelectedRow();
        
        if(index >= 0){
            pnlViewVehicleController.deleteVehicle(index);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para eliminar.", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
